# Generated by Django 3.2.15 on 2022-09-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_a_story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.CharField(default='vault', max_length=10),
        ),
    ]
