# Generated by Django 3.2.15 on 2022-09-29 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrow_a_story', '0003_alter_book_bookmarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookmarked',
            field=models.ManyToManyField(related_name='bookmarked', to=settings.AUTH_USER_MODEL),
        ),
    ]
