# Generated by Django 3.2.15 on 2022-10-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_a_story', '0005_user_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='return_status',
            field=models.BooleanField(default=False),
        ),
    ]
